[project]
name = "haybale-visiongraph"
version = "0.0.37"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "depthai~=2.30", 
    "fastapi", 
    "haybale-core>=0.0.32", 
    "haywire-core>=0.1.0", 
    "nicegui>=3.12.1", 
    "numpy", 
    "opencv-contrib-python>=5.0.0.93", 
    "typing_extensions>=4.15.0", 
    "visiongraph[onnx,openvino,mediapipe]"]
description = "Visiongraph is a computer-vision pipeline library designed to simplify the prototyping of image-based algorithms"
keywords = ["computer vision", "machine learning", "camera", "image capture"]

[[project.authors]]
name = "cansik"

[[project.authors]]
name = "maybites"
[project.urls]
Homepage = "https://github.com/going-haywire/haybale-visiongraph"
Documentation = "https://cansik.github.io/visiongraph/visiongraph.html#documentation"
Issues = "https://github.com/going-haywire/haybale-visiongraph/issues"
Source = "https://github.com/going-haywire/haybale-visiongraph"
[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.license]
text = "MIT"

[project.entry-points."haywire.libraries"]
visiongraph = "haybale_visiongraph:Library"

[tool.hatch.build.targets.wheel]
packages = [ "haybale_visiongraph",]

[tool.hatch.build.targets.sdist]
include = [ "haybale_visiongraph/", "README.md",]
